apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-db
  template:
    metadata:
      labels:
        app: django-db
    spec:
      volumes:
        - name: db-files
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
        - name: django-db
          image: postgres:12
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-files
          env:
            - name: POSTGRES_USER
              value: dev
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: blogdb

          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
spec:
  selector:
    app: django-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432